{% set name = "dmqclib" %}
{% set version = "0.6.3" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50c615e6307b09f7291c9843223394bc870784634ffc5b0d20545a2212de787f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - joblib >=1.4.2
    - jsonschema >=4.23.0
    - numpy >=2.2
    - pandas >=2.2
    - polars >=1.30.0
    - pyarrow >=19.0.0
    - pyyaml >=6.0.2
    - scikit-learn >=1.6.1
    - xgboost >=3.0.2

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - dmqclib
  commands:
    - pip check

about:
  summary: This package aims to offer helper functions that simplify model building and evaluation
  license: MIT
  license_file: LICENSE
  home: https://github.com/AIQC-Hub/dmqclib

extra:
  recipe-maintainers:
    - takayasaito
